version: "3.2"

services:

    mongo:
        image: mongo
        ports:
            - target: 27017
              published: 27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass